gems:
    - jekyll-redirect-from
    - jekyll-sitemap

# Site settings
title: allegro.tech
menu: false
#email: kariera@allegro.pl
description: "We use Open Source solutions on a daily basis here at Allegro Group. Why not work on our karma and give something in return? Welcome to our open source technology blog."
name: allegro.tech blog
baseurl: ""
url: "http://allegro.tech"
twitter_username: AllegroTechBlog
github_username:  allegro
facebook_username: allegro.tech
google_plus_id: +AllegroTechBlog
meetup_username: allegrotech
slideshare_username: allegrotech

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

kramdown:
    input: GFM
    coderay_line_numbers: nil

sass:
    sass_dir: css/partials

permalink: /:year/:month/:title.html

